name: vegobolt
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Added packages for secure local storage and hashing
  crypto: ^3.0.2
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  flutter_web_auth_2: ^4.0.0
  url_launcher: ^6.2.5
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/vegobolt_logo.png